site_name: Spokane Tech

theme:
  name: material
  logo: assets/img/spokanetech.png
  favicon: assets/img/spokanetech.png
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .

nav:
  - Blog:
    - index.md 
