authors:
  spokanetech:
    name: Spokane Tech
    description: Organizer
    avatar: /assets/img/spokanetech.png

  joeriddles:
    name: Joseph Riddle
    description: Organizer
    avatar: https://github.com/joeriddles.png
